### ISSUE TITLE
Tracking issue for migrating/deleting old codegen tests

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#1345]
We recently deleted the old LLVM JIT backend. We renamed all non-new-codegen C tests to `*.old.c` and they are currently ignored.

Some of those tests need porting, some can be deleted. This issue tracks this progress.

## Need to be ported

 - [ ] arg_mapping_callee.old.c
 - [ ] awkward_unmappable.old.c
 - [ ] bf.old.c
 - [ ] call_args.old.c
 - [ ] call_ext_in_obj.old.c
 - [ ] call_ext_simple.old.c
 - [ ] calls_double.old.c
 - [ ] choice.old.c
 - [ ] conditionals.old.c
 - [ ] constexpr.old.c
 - [ ] const_global.old.c
 - [ ] fib.old.c
 - [ ] funcptrarg_hasir.old.c
 - [ ] funcptrarg_noir.old.c
 - [ ] indirect_branch.old.c
 - [ ] indirect_external_function_call.old.c
 - [ ] internal_linkage_same_obj.old.c
 - [ ] intrinsic_noinline.old.c
 - [ ] intrinsics.old.c
 - [ ] lifetime_intrinsics.old.c
 - [ ] loopy_funcs_not_inlined_by_default.old.c
 - [ ] many_threads_many_locs.old.c
 - [ ] many_threads_one_loc.old.c
 - [ ] mutable_global.old.c
 - [ ] nested_sidetrace.old.c
 - [ ] nested_writetoptr.old.c
 - [ ] noopts.old.c
 - [ ] not_loopy_funcs_inlined_by_default.old.c
 - [ ] no_trace_annotation2.old.c
 - [ ] no_trace_annotation.old.c
 - [ ] promote_expr.old.c
 - [ ] ptr_global.old.c
 - [ ] pt_zero_len_call.old.c
 - [ ] qsort.old.c
 - [ ] reentrant.old.c
 - [ ] rel_path.old.c
 - [ ] resume_and_branch.old.c
 - [ ] side-trace.old.c
 - [ ] sidetrace_phinode.old.c
 - [ ] sidetrace_while.old.c
 - [ ] simple_nested.old.c
 - [ ] simple_non_serialised.old.c
 - [ ] smmultisrc2.old.c
 - [ ] smmultisrc.old.c
 - [ ] stats1.old.c
 - [ ] stats2.old.c
 - [ ] stats3.old.c
 - [ ] stats4.old.c
 - [ ] strarray.old.c
 - [ ] struct_simple.old.c
 - [ ] trace_too_long_hwt.old.c
 - [ ] trace_too_long.old.c
 - [ ] unmapped_setjmp.old.c
 - [ ] unroll_safe_implies_noinline.old.c
 - [ ] unroll_safe_inlines.old.c
 - [ ] varargs_inlined.old.c
 - [ ] varargs.old.c
 - [ ] void_ret.old.c
 - [ ] yk_unroll_safe_vs_yk_outline.old.c

## Duplicate tests that can be removed.

 - [ ] debuginfo.old.c (dup of aot_debuginfo.c)
 - [ ] direct_recursion.old.c (dup of outline_recursion.c)
 - [ ] mutual_recursion.old.c (dup of outline_recursion_indirect.c)
 - [ ] inline_asm_call.old.c (dup of inline_asm.c)

## Irrelevant tests that can be deleted.

 - [ ] interp_inside_call2.old.c (designed as blackholing test)
 - [ ] interp_inside_call.old.c (designed as blackholing test)
 - [ ] outlinebase_bug.old.c (tests an old outlining mechanism)
 - [ ] promote_not_great.old.c (tests limitation of an old promote mechanism)

**Comment by vext01** [comment]
There's a lot of work to be done here. Is it worth spreading the load?

**Comment by vext01** [comment]
OK, I've migrated all the tests apart from the side-tracing tests.

I'll reassign this to @ptersilie for when he revisists side-tracing.
