### ISSUE TITLE
Tracking issue for unconditionally ignored C tests.

### ISSUE THREAD

**Issue by vext01** [ykjit/yk#1358]
There are quite a few unconditionally ignored C tests that fail for varying reasons. This issue tracks them.

## crashes trace builder in `handle_operand()`

 - [ ] `funcptrarg_hasir.c`
 - [ ] `indirect_external_function_call.c`
 - [ ] `qsort.c`

## designed to test LLVM constant GEP expressions , but -O0 doesn't emit such code.

 - [ ] `constexpr.c`

## crashes ykllvm's BlockDisambiguate pass.

 - [ ] `indirect_branch.c`:

## not yet implemented: Unimplemented { tyidx: TyIdx(6), llvm_inst_str: "  call void @llvm.memcpy.p0

 - [ ] `intrinsic_noinline.c`

## shadow stack can't do threads

 - [ ] `many_threads_many_locs.c`
 - [ ] `many_threads_one_loc.c`
 - [ ] `stats2.c`

## trace builder can't handle unmappable code "calling back" to mappable code.

 - [ ] `reentrant.c`

## not yet implemented: ran out of gp regs

 - [ ] `smmultisrc.c`
 - [ ] `smmultisrc2.c`

## Crashes on unimplemneted setjmp instruction

 - [ ] `stats3.c`

## doesn't trigger expected "trace too long"

 - [ ] `trace_too_long.c`

## Truncation currently always truncates to i32, no matter the target type

(maybe this is OK and we can delete/ammend the test without functional changes?)

 - [ ] `truncate.c`

## trace-compilation-aborted: dlsym("llvm.va_start") returned NULL

 - [ ] `varargs_inlined.c`
